"""add monitoring tables

Revision ID: 06671bbc114e
Revises: 5d543914f3c6
Create Date: 2026-07-24 15:06:23.755449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06671bbc114e'
down_revision: Union[str, Sequence[str], None] = '5d543914f3c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('component', sa.String(length=50), nullable=False),
    sa.Column('component_instance', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_', sa.JSON(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_component'), ['component'], unique=False)
        batch_op.create_index('ix_alerts_open', ['status', 'severity', 'last_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_status'), ['status'], unique=False)

    op.create_table('health_checks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('component', sa.String(length=50), nullable=False),
    sa.Column('component_instance', sa.String(length=255), nullable=True),
    sa.Column('check_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('metadata_', sa.JSON(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_checks'))
    )
    with op.batch_alter_table('health_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_checks_component'), ['component'], unique=False)
        batch_op.create_index('ix_health_checks_component_checked_at', ['component', 'checked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_checks_component_instance'), ['component_instance'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_checks_status'), ['status'], unique=False)

    op.create_table('health_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('overall_status', sa.String(length=20), nullable=False),
    sa.Column('data_quality_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('freshness_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('availability_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_snapshots'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('health_snapshots')
    with op.batch_alter_table('health_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_checks_status'))
        batch_op.drop_index(batch_op.f('ix_health_checks_component_instance'))
        batch_op.drop_index('ix_health_checks_component_checked_at')
        batch_op.drop_index(batch_op.f('ix_health_checks_component'))

    op.drop_table('health_checks')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_alerts_severity'))
        batch_op.drop_index('ix_alerts_open')
        batch_op.drop_index(batch_op.f('ix_alerts_component'))
        batch_op.drop_index(batch_op.f('ix_alerts_category'))

    op.drop_table('alerts')
    # ### end Alembic commands ###
