"""add intelligence tables

Revision ID: 35de8300bf07
Revises: 06671bbc114e
Create Date: 2026-07-24 15:28:27.049883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35de8300bf07'
down_revision: Union[str, Sequence[str], None] = '06671bbc114e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insights',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('metadata_', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insights'))
    )
    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insights_category'), ['category'], unique=False)
        batch_op.create_index('ix_insights_category_created', ['category', 'created_at'], unique=False)
        batch_op.create_index('ix_insights_severity', ['severity'], unique=False)

    op.create_table('trend_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('metric', sa.String(length=50), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('baseline', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('delta', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trend_snapshots'))
    )
    with op.batch_alter_table('trend_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trend_snapshots_metric'), ['metric'], unique=False)
        batch_op.create_index('ix_trend_snapshots_metric_period', ['metric', 'period'], unique=False)
        batch_op.create_index(batch_op.f('ix_trend_snapshots_period'), ['period'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trend_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trend_snapshots_period'))
        batch_op.drop_index('ix_trend_snapshots_metric_period')
        batch_op.drop_index(batch_op.f('ix_trend_snapshots_metric'))

    op.drop_table('trend_snapshots')
    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.drop_index('ix_insights_severity')
        batch_op.drop_index('ix_insights_category_created')
        batch_op.drop_index(batch_op.f('ix_insights_category'))

    op.drop_table('insights')
    # ### end Alembic commands ###
