"""initial canonical commerce schema

Revision ID: 37bb8178cc8b
Revises: 
Create Date: 2026-07-16 15:20:51.953519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37bb8178cc8b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('condition', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_rules')),
    sa.UniqueConstraint('organization_id', 'business_id', 'store_id', 'code', name='uq_business_rule_code')
    )
    with op.batch_alter_table('business_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_rules_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_rules_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_rules_store_id'), ['store_id'], unique=False)

    op.create_table('campaigns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('marketplace_campaign_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('campaign_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('budget', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('marketplace_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns')),
    sa.UniqueConstraint('organization_id', 'business_id', 'store_id', 'marketplace_campaign_id', name='uq_campaign_marketplace_id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_store_id'), ['store_id'], unique=False)

    op.create_table('commerce_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_quality_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('confidence_level', sa.String(length=20), nullable=False),
    sa.Column('sources_fresh', sa.JSON(), nullable=False),
    sa.Column('sources_stale', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('alerts', sa.JSON(), nullable=False),
    sa.Column('risks', sa.JSON(), nullable=False),
    sa.Column('opportunities', sa.JSON(), nullable=False),
    sa.Column('anomalies', sa.JSON(), nullable=False),
    sa.Column('todays_focus', sa.JSON(), nullable=False),
    sa.Column('last_sync', sa.JSON(), nullable=False),
    sa.Column('data_quality', sa.JSON(), nullable=False),
    sa.Column('marketplace_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commerce_states'))
    )
    with op.batch_alter_table('commerce_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commerce_states_business_id'), ['business_id'], unique=False)
        batch_op.create_index('ix_commerce_states_generated_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_commerce_states_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_commerce_states_store_id'), ['store_id'], unique=False)

    op.create_table('data_quality_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('issue_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_quality_events'))
    )
    with op.batch_alter_table('data_quality_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_quality_events_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_quality_events_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_data_quality_events_severity', ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_quality_events_store_id'), ['store_id'], unique=False)

    op.create_table('expenses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('incurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('marketplace_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenses'))
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_business_id'), ['business_id'], unique=False)
        batch_op.create_index('ix_expenses_category_incurred_at', ['category', 'incurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_store_id'), ['store_id'], unique=False)

    op.create_table('kpis',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('formula', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('freshness', sa.DateTime(timezone=True), nullable=False),
    sa.Column('marketplace_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kpis')),
    sa.UniqueConstraint('organization_id', 'business_id', 'store_id', 'code', name='uq_kpi_code')
    )
    with op.batch_alter_table('kpis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kpis_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kpis_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kpis_store_id'), ['store_id'], unique=False)

    op.create_table('marketplaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marketplaces')),
    sa.UniqueConstraint('code', name=op.f('uq_marketplaces_code'))
    )
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('marketplace_order_id', sa.String(length=255), nullable=False),
    sa.Column('order_number', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('fulfillment_status', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('discount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('commission', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('shipping_subsidy', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('marketplace_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('organization_id', 'business_id', 'store_id', 'marketplace_order_id', name='uq_order_marketplace_id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_orders_status_ordered_at', ['status', 'ordered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_store_id'), ['store_id'], unique=False)

    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('slug', name=op.f('uq_organizations_slug'))
    )
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('selling_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('marketplace_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_store_id'), ['store_id'], unique=False)
        batch_op.create_index('ix_products_tenant_sku', ['organization_id', 'business_id', 'store_id', 'sku'], unique=False)

    op.create_table('reconciliation_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('source_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('computed_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('difference', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tolerance', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconciliation_events'))
    )
    with op.batch_alter_table('reconciliation_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reconciliation_events_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_events_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_reconciliation_events_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_events_store_id'), ['store_id'], unique=False)

    op.create_table('ads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('marketplace_ad_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('ad_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('marketplace_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_ads_campaign_id_campaigns')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ads')),
    sa.UniqueConstraint('organization_id', 'business_id', 'store_id', 'marketplace_ad_id', name='uq_ad_marketplace_id')
    )
    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ads_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_store_id'), ['store_id'], unique=False)

    op.create_table('businesses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_businesses_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_businesses'))
    )
    op.create_table('kpi_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kpi_id', sa.String(length=36), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('marketplace_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['kpi_id'], ['kpis.id'], name=op.f('fk_kpi_history_kpi_id_kpis')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kpi_history'))
    )
    with op.batch_alter_table('kpi_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kpi_history_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kpi_history_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_kpi_history_recorded_at', ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_kpi_history_store_id'), ['store_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('marketplace_payment_id', sa.String(length=255), nullable=True),
    sa.Column('payment_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('marketplace_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_payments_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_business_id'), ['business_id'], unique=False)
        batch_op.create_index('ix_payments_order_id', ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_store_id'), ['store_id'], unique=False)

    op.create_table('rule_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=False),
    sa.Column('triggered', sa.Boolean(), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=True),
    sa.Column('outputs', sa.JSON(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['business_rules.id'], name=op.f('fk_rule_executions_rule_id_business_rules')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_executions'))
    )
    with op.batch_alter_table('rule_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_executions_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_executions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_executions_store_id'), ['store_id'], unique=False)

    op.create_table('variants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('sku', sa.String(length=255), nullable=False),
    sa.Column('barcode', sa.String(length=255), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('selling_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('marketplace_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_variants_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_variants')),
    sa.UniqueConstraint('organization_id', 'business_id', 'store_id', 'sku', name='uq_variant_sku_per_store')
    )
    with op.batch_alter_table('variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_variants_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_variants_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_variants_store_id'), ['store_id'], unique=False)

    op.create_table('ad_performances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ad_id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('spend', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('roas', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('marketplace_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], name=op.f('fk_ad_performances_ad_id_ads')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_ad_performances_campaign_id_campaigns')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ad_performances')),
    sa.UniqueConstraint('ad_id', 'date', name='uq_ad_performance_date')
    )
    with op.batch_alter_table('ad_performances', schema=None) as batch_op:
        batch_op.create_index('ix_ad_performance_date', ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_performances_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_performances_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_performances_store_id'), ['store_id'], unique=False)

    op.create_table('inventory',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('variant_id', sa.String(length=36), nullable=False),
    sa.Column('quantity_available', sa.Integer(), nullable=False),
    sa.Column('quantity_reserved', sa.Integer(), nullable=False),
    sa.Column('warehouse_location', sa.String(length=255), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('marketplace_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], name=op.f('fk_inventory_variant_id_variants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory'))
    )
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_store_id'), ['store_id'], unique=False)
        batch_op.create_index('ix_inventory_tenant_variant', ['organization_id', 'business_id', 'store_id', 'variant_id'], unique=False)

    op.create_table('order_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('variant_id', sa.String(length=36), nullable=True),
    sa.Column('product_name', sa.String(length=500), nullable=False),
    sa.Column('variant_name', sa.String(length=500), nullable=True),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('commission', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('marketplace_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders')),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], name=op.f('fk_order_items_variant_id_variants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_store_id'), ['store_id'], unique=False)

    op.create_table('revenue',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('payment_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('recognized_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('marketplace_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_revenue_order_id_orders')),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_revenue_payment_id_payments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revenue'))
    )
    with op.batch_alter_table('revenue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revenue_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_revenue_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_revenue_recognized_at', ['recognized_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_revenue_store_id'), ['store_id'], unique=False)

    op.create_table('stores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('marketplace_id', sa.String(length=36), nullable=False),
    sa.Column('marketplace_store_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('auth_config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_stores_business_id_businesses')),
    sa.ForeignKeyConstraint(['marketplace_id'], ['marketplaces.id'], name=op.f('fk_stores_marketplace_id_marketplaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stores')),
    sa.UniqueConstraint('business_id', 'marketplace_id', 'marketplace_store_id', name='uq_store_marketplace_identifier')
    )
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stores_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stores_store_id'), ['store_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stores_store_id'))
        batch_op.drop_index(batch_op.f('ix_stores_organization_id'))

    op.drop_table('stores')
    with op.batch_alter_table('revenue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revenue_store_id'))
        batch_op.drop_index('ix_revenue_recognized_at')
        batch_op.drop_index(batch_op.f('ix_revenue_organization_id'))
        batch_op.drop_index(batch_op.f('ix_revenue_business_id'))

    op.drop_table('revenue')
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_store_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_organization_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_business_id'))

    op.drop_table('order_items')
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_index('ix_inventory_tenant_variant')
        batch_op.drop_index(batch_op.f('ix_inventory_store_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_organization_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_business_id'))

    op.drop_table('inventory')
    with op.batch_alter_table('ad_performances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ad_performances_store_id'))
        batch_op.drop_index(batch_op.f('ix_ad_performances_organization_id'))
        batch_op.drop_index(batch_op.f('ix_ad_performances_business_id'))
        batch_op.drop_index('ix_ad_performance_date')

    op.drop_table('ad_performances')
    with op.batch_alter_table('variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_variants_store_id'))
        batch_op.drop_index(batch_op.f('ix_variants_organization_id'))
        batch_op.drop_index(batch_op.f('ix_variants_business_id'))

    op.drop_table('variants')
    with op.batch_alter_table('rule_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_executions_store_id'))
        batch_op.drop_index(batch_op.f('ix_rule_executions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_rule_executions_business_id'))

    op.drop_table('rule_executions')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_store_id'))
        batch_op.drop_index(batch_op.f('ix_payments_organization_id'))
        batch_op.drop_index('ix_payments_order_id')
        batch_op.drop_index(batch_op.f('ix_payments_business_id'))

    op.drop_table('payments')
    with op.batch_alter_table('kpi_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kpi_history_store_id'))
        batch_op.drop_index('ix_kpi_history_recorded_at')
        batch_op.drop_index(batch_op.f('ix_kpi_history_organization_id'))
        batch_op.drop_index(batch_op.f('ix_kpi_history_business_id'))

    op.drop_table('kpi_history')
    op.drop_table('businesses')
    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ads_store_id'))
        batch_op.drop_index(batch_op.f('ix_ads_organization_id'))
        batch_op.drop_index(batch_op.f('ix_ads_business_id'))

    op.drop_table('ads')
    with op.batch_alter_table('reconciliation_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reconciliation_events_store_id'))
        batch_op.drop_index('ix_reconciliation_events_status')
        batch_op.drop_index(batch_op.f('ix_reconciliation_events_organization_id'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_events_business_id'))

    op.drop_table('reconciliation_events')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('ix_products_tenant_sku')
        batch_op.drop_index(batch_op.f('ix_products_store_id'))
        batch_op.drop_index(batch_op.f('ix_products_organization_id'))
        batch_op.drop_index(batch_op.f('ix_products_business_id'))

    op.drop_table('products')
    op.drop_table('organizations')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_store_id'))
        batch_op.drop_index('ix_orders_status_ordered_at')
        batch_op.drop_index(batch_op.f('ix_orders_organization_id'))
        batch_op.drop_index(batch_op.f('ix_orders_business_id'))

    op.drop_table('orders')
    op.drop_table('marketplaces')
    with op.batch_alter_table('kpis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kpis_store_id'))
        batch_op.drop_index(batch_op.f('ix_kpis_organization_id'))
        batch_op.drop_index(batch_op.f('ix_kpis_business_id'))

    op.drop_table('kpis')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_store_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_organization_id'))
        batch_op.drop_index('ix_expenses_category_incurred_at')
        batch_op.drop_index(batch_op.f('ix_expenses_business_id'))

    op.drop_table('expenses')
    with op.batch_alter_table('data_quality_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_quality_events_store_id'))
        batch_op.drop_index('ix_data_quality_events_severity')
        batch_op.drop_index(batch_op.f('ix_data_quality_events_organization_id'))
        batch_op.drop_index(batch_op.f('ix_data_quality_events_business_id'))

    op.drop_table('data_quality_events')
    with op.batch_alter_table('commerce_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commerce_states_store_id'))
        batch_op.drop_index(batch_op.f('ix_commerce_states_organization_id'))
        batch_op.drop_index('ix_commerce_states_generated_at')
        batch_op.drop_index(batch_op.f('ix_commerce_states_business_id'))

    op.drop_table('commerce_states')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_store_id'))
        batch_op.drop_index(batch_op.f('ix_campaigns_organization_id'))
        batch_op.drop_index(batch_op.f('ix_campaigns_business_id'))

    op.drop_table('campaigns')
    with op.batch_alter_table('business_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_rules_store_id'))
        batch_op.drop_index(batch_op.f('ix_business_rules_organization_id'))
        batch_op.drop_index(batch_op.f('ix_business_rules_business_id'))

    op.drop_table('business_rules')
    # ### end Alembic commands ###
