"""add decision engine tables

Revision ID: 4a3f8c2e1b0d
Revises: 1c59369346f6
Create Date: 2026-07-24 16:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a3f8c2e1b0d'
down_revision: Union[str, Sequence[str], None] = '1c59369346f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('expected_impact', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions'))
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decisions_category'), ['category'], unique=False)
        batch_op.create_index('ix_decisions_category_status', ['category', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_severity'), ['severity'], unique=False)
        batch_op.create_index('ix_decisions_severity_created', ['severity', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_status'), ['status'], unique=False)

    op.create_table('decision_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('decision_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], name=op.f('fk_decision_evidence_decision_id_decisions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decision_evidence'))
    )
    with op.batch_alter_table('decision_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decision_evidence_decision_id'), ['decision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_evidence_source_type'), ['source_type'], unique=False)

    op.create_table('decision_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('decision_id', sa.String(length=36), nullable=False),
    sa.Column('old_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('changed_by', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], name=op.f('fk_decision_history_decision_id_decisions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decision_history'))
    )
    with op.batch_alter_table('decision_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decision_history_decision_id'), ['decision_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decision_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decision_history_decision_id'))

    op.drop_table('decision_history')
    with op.batch_alter_table('decision_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decision_evidence_source_type'))
        batch_op.drop_index(batch_op.f('ix_decision_evidence_decision_id'))

    op.drop_table('decision_evidence')
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decisions_status'))
        batch_op.drop_index('ix_decisions_severity_created')
        batch_op.drop_index(batch_op.f('ix_decisions_severity'))
        batch_op.drop_index('ix_decisions_category_status')
        batch_op.drop_index(batch_op.f('ix_decisions_category'))

    op.drop_table('decisions')
    # ### end Alembic commands ###
