"""add execution engine tables

Revision ID: 7b2e1d9f0c4a
Revises: 4a3f8c2e1b0d
Create Date: 2026-07-24 17:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b2e1d9f0c4a'
down_revision: Union[str, Sequence[str], None] = '4a3f8c2e1b0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('decision_id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('metadata_', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], name=op.f('fk_execution_plans_decision_id_decisions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_plans'))
    )
    with op.batch_alter_table('execution_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_plans_action_type'), ['action_type'], unique=False)
        batch_op.create_index('ix_execution_plans_decision_status', ['decision_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_plans_status'), ['status'], unique=False)
        batch_op.create_index('ix_execution_plans_status_created', ['status', 'created_at'], unique=False)

    op.create_table('execution_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('rollback_supported', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['execution_plans.id'], name=op.f('fk_execution_steps_plan_id_execution_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_steps'))
    )
    with op.batch_alter_table('execution_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_steps_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index('ix_execution_steps_plan_id_step_number', ['plan_id', 'step_number'], unique=False)

    op.create_table('execution_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('old_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('changed_by', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['execution_plans.id'], name=op.f('fk_execution_history_plan_id_execution_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_history'))
    )
    with op.batch_alter_table('execution_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_history_plan_id'), ['plan_id'], unique=False)

    op.create_table('execution_audit',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('event', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['execution_plans.id'], name=op.f('fk_execution_audit_plan_id_execution_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_audit'))
    )
    with op.batch_alter_table('execution_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_audit_event'), ['event'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_audit_plan_id'), ['plan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('execution_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_audit_plan_id'))
        batch_op.drop_index(batch_op.f('ix_execution_audit_event'))

    op.drop_table('execution_audit')
    with op.batch_alter_table('execution_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_history_plan_id'))

    op.drop_table('execution_history')
    with op.batch_alter_table('execution_steps', schema=None) as batch_op:
        batch_op.drop_index('ix_execution_steps_plan_id_step_number')
        batch_op.drop_index(batch_op.f('ix_execution_steps_plan_id'))

    op.drop_table('execution_steps')
    with op.batch_alter_table('execution_plans', schema=None) as batch_op:
        batch_op.drop_index('ix_execution_plans_status_created')
        batch_op.drop_index(batch_op.f('ix_execution_plans_status'))
        batch_op.drop_index('ix_execution_plans_decision_status')
        batch_op.drop_index(batch_op.f('ix_execution_plans_action_type'))

    op.drop_table('execution_plans')
    # ### end Alembic commands ###
