"""add event bus and workflow orchestration tables

Revision ID: 9c1d2e3f4a5b
Revises: 7b2e1d9f0c4a
Create Date: 2026-07-24 18:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c1d2e3f4a5b'
down_revision: Union[str, Sequence[str], None] = '7b2e1d9f0c4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('aggregate_type', sa.String(length=50), nullable=False),
    sa.Column('aggregate_id', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('metadata_', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_aggregate_id'), ['aggregate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_aggregate_type'), ['aggregate_type'], unique=False)
        batch_op.create_index('ix_events_aggregate', ['aggregate_type', 'aggregate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index('ix_events_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_status'), ['status'], unique=False)
        batch_op.create_index('ix_events_type_status', ['event_type', 'status'], unique=False)

    op.create_table('event_subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('handler_name', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('metadata_', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_subscriptions'))
    )
    with op.batch_alter_table('event_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_subscriptions_event_type'), ['event_type'], unique=False)
        batch_op.create_index('ix_event_subscriptions_type_handler', ['event_type', 'handler_name'], unique=True)

    op.create_table('distributed_locks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lock_name', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.String(length=255), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_distributed_locks'))
    )
    with op.batch_alter_table('distributed_locks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_distributed_locks_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_distributed_locks_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_distributed_locks_lock_name'), ['lock_name'], unique=True)

    op.create_table('workflow_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('trigger_event_id', sa.String(length=36), nullable=True),
    sa.Column('metadata_', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trigger_event_id'], ['events.id'], name=op.f('fk_workflow_jobs_trigger_event_id_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_jobs'))
    )
    with op.batch_alter_table('workflow_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_jobs_name_status'), ['workflow_name', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_jobs_status'), ['status'], unique=False)
        batch_op.create_index('ix_workflow_jobs_status_scheduled', ['status', 'scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_jobs_trigger_event_id'), ['trigger_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_jobs_workflow_name'), ['workflow_name'], unique=False)

    op.create_table('dead_letter_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retry_allowed', sa.Boolean(), nullable=False),
    sa.Column('metadata_', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_dead_letter_events_event_id_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dead_letter_events'))
    )
    with op.batch_alter_table('dead_letter_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dead_letter_events_event_id'), ['event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_dead_letter_events_failed_at'), ['failed_at'], unique=False)

    op.create_table('workflow_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('old_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['workflow_jobs.id'], name=op.f('fk_workflow_history_job_id_workflow_jobs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_history'))
    )
    with op.batch_alter_table('workflow_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_history_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_history_job_id'))

    op.drop_table('workflow_history')
    with op.batch_alter_table('dead_letter_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dead_letter_events_failed_at'))
        batch_op.drop_index(batch_op.f('ix_dead_letter_events_event_id'))

    op.drop_table('dead_letter_events')
    with op.batch_alter_table('workflow_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_jobs_workflow_name'))
        batch_op.drop_index(batch_op.f('ix_workflow_jobs_trigger_event_id'))
        batch_op.drop_index('ix_workflow_jobs_status_scheduled')
        batch_op.drop_index(batch_op.f('ix_workflow_jobs_status'))
        batch_op.drop_index('ix_workflow_jobs_name_status')

    op.drop_table('workflow_jobs')
    with op.batch_alter_table('distributed_locks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_distributed_locks_lock_name'))
        batch_op.drop_index(batch_op.f('ix_distributed_locks_job_id'))
        batch_op.drop_index(batch_op.f('ix_distributed_locks_expires_at'))

    op.drop_table('distributed_locks')
    with op.batch_alter_table('event_subscriptions', schema=None) as batch_op:
        batch_op.drop_index('ix_event_subscriptions_type_handler')
        batch_op.drop_index(batch_op.f('ix_event_subscriptions_event_type'))

    op.drop_table('event_subscriptions')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_type_status')
        batch_op.drop_index(batch_op.f('ix_events_status'))
        batch_op.drop_index('ix_events_status_created')
        batch_op.drop_index(batch_op.f('ix_events_event_type'))
        batch_op.drop_index('ix_events_aggregate')
        batch_op.drop_index(batch_op.f('ix_events_aggregate_type'))
        batch_op.drop_index(batch_op.f('ix_events_aggregate_id'))

    op.drop_table('events')
    # ### end Alembic commands ###
