"""add ingestion bounded context schema

Revision ID: e467e0be346a
Revises: 37bb8178cc8b
Create Date: 2026-07-17 21:26:18.981942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e467e0be346a'
down_revision: Union[str, Sequence[str], None] = '37bb8178cc8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_payloads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sync_run_id', sa.String(length=36), nullable=False),
    sa.Column('marketplace_code', sa.String(length=50), nullable=False),
    sa.Column('store_id', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('external_entity_id', sa.String(length=255), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('connector_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_payloads')),
    sa.UniqueConstraint('marketplace_code', 'store_id', 'entity_type', 'external_entity_id', 'payload_hash', name='uq_raw_payload_identity')
    )
    with op.batch_alter_table('raw_payloads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_payloads_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_payloads_external_entity_id'), ['external_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_payloads_marketplace_code'), ['marketplace_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_payloads_store_id'), ['store_id'], unique=False)
        batch_op.create_index('ix_raw_payloads_sync_run', ['sync_run_id', 'entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_payloads_sync_run_id'), ['sync_run_id'], unique=False)

    op.create_table('sync_checkpoints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connector_code', sa.String(length=50), nullable=False),
    sa.Column('store_id', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('sync_mode', sa.String(length=20), nullable=False),
    sa.Column('cursor', sa.String(length=512), nullable=True),
    sa.Column('last_successful_sync_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('connector_version', sa.String(length=50), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_checkpoints')),
    sa.UniqueConstraint('connector_code', 'store_id', 'entity_type', 'sync_mode', name='uq_sync_checkpoint_scope')
    )
    with op.batch_alter_table('sync_checkpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_checkpoints_connector_code'), ['connector_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_checkpoints_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_checkpoints_store_id'), ['store_id'], unique=False)

    op.create_table('sync_provenance',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('canonical_entity_type', sa.String(length=50), nullable=False),
    sa.Column('canonical_entity_id', sa.String(length=36), nullable=False),
    sa.Column('raw_payload_id', sa.String(length=36), nullable=False),
    sa.Column('marketplace_code', sa.String(length=50), nullable=False),
    sa.Column('store_id', sa.String(length=255), nullable=False),
    sa.Column('external_entity_id', sa.String(length=255), nullable=False),
    sa.Column('sync_run_id', sa.String(length=36), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('connector_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_provenance')),
    sa.UniqueConstraint('canonical_entity_type', 'canonical_entity_id', name='uq_sync_provenance_canonical')
    )
    with op.batch_alter_table('sync_provenance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_provenance_canonical_entity_id'), ['canonical_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_provenance_canonical_entity_type'), ['canonical_entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_provenance_external_entity_id'), ['external_entity_id'], unique=False)
        batch_op.create_index('ix_sync_provenance_lookup', ['marketplace_code', 'store_id', 'external_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_provenance_marketplace_code'), ['marketplace_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_provenance_raw_payload_id'), ['raw_payload_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_provenance_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_provenance_sync_run_id'), ['sync_run_id'], unique=False)

    op.create_table('sync_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('connector_code', sa.String(length=50), nullable=False),
    sa.Column('store_id', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('sync_mode', sa.String(length=20), nullable=False),
    sa.Column('cursor', sa.String(length=512), nullable=True),
    sa.Column('connector_version', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('records_received', sa.Integer(), nullable=False),
    sa.Column('records_persisted', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_runs'))
    )
    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_runs_connector_code'), ['connector_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_runs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_runs_store_id'), ['store_id'], unique=False)
        batch_op.create_index('ix_sync_runs_store_started', ['store_id', 'started_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_sync_runs_store_started')
        batch_op.drop_index(batch_op.f('ix_sync_runs_store_id'))
        batch_op.drop_index(batch_op.f('ix_sync_runs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_sync_runs_connector_code'))

    op.drop_table('sync_runs')
    with op.batch_alter_table('sync_provenance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_provenance_sync_run_id'))
        batch_op.drop_index(batch_op.f('ix_sync_provenance_store_id'))
        batch_op.drop_index(batch_op.f('ix_sync_provenance_raw_payload_id'))
        batch_op.drop_index(batch_op.f('ix_sync_provenance_marketplace_code'))
        batch_op.drop_index('ix_sync_provenance_lookup')
        batch_op.drop_index(batch_op.f('ix_sync_provenance_external_entity_id'))
        batch_op.drop_index(batch_op.f('ix_sync_provenance_canonical_entity_type'))
        batch_op.drop_index(batch_op.f('ix_sync_provenance_canonical_entity_id'))

    op.drop_table('sync_provenance')
    with op.batch_alter_table('sync_checkpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_checkpoints_store_id'))
        batch_op.drop_index(batch_op.f('ix_sync_checkpoints_entity_type'))
        batch_op.drop_index(batch_op.f('ix_sync_checkpoints_connector_code'))

    op.drop_table('sync_checkpoints')
    with op.batch_alter_table('raw_payloads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_payloads_sync_run_id'))
        batch_op.drop_index('ix_raw_payloads_sync_run')
        batch_op.drop_index(batch_op.f('ix_raw_payloads_store_id'))
        batch_op.drop_index(batch_op.f('ix_raw_payloads_marketplace_code'))
        batch_op.drop_index(batch_op.f('ix_raw_payloads_external_entity_id'))
        batch_op.drop_index(batch_op.f('ix_raw_payloads_entity_type'))

    op.drop_table('raw_payloads')
    # ### end Alembic commands ###
