"""Mission Control — Web COO Command Center.

The default landing page for the CommerceOS Web COO Dashboard. It surfaces:
- Business today (revenue, orders, profit, ads, ROAS, inventory health)
- System health and data freshness
- Attention items (alerts, decisions, insights, low stock, failed jobs)
- COO brief generated by the COO Interface
- Quick navigation to all COO sections

All data is read through the canonical WebCOODashboardService. No direct SQL,
no marketplace mutations, no duplicated business logic.
"""
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Dict, List

import pandas as pd
import streamlit as st

BASE_DIR = Path(__file__).parent.parent
import sys
sys.path.insert(0, str(BASE_DIR))

from commerceos.config.settings import get_settings
from commerceos.coo.web_service import WebCOODashboardService
from commerceos.platform.database.connection import get_session

st.set_page_config(
    page_title="CommerceOS — Command Center",
    page_icon="🦊",
    layout="wide",
    initial_sidebar_state="expanded",
)

SETTINGS = get_settings()
STORE_ID = st.secrets.get("COMMERCEOS_STORE_ID", "store-ppm-001")


@st.cache_resource(show_spinner=False)
def _get_session():
    return get_session(SETTINGS.database_url)


def _currency(value: float) -> str:
    try:
        return f"Rp {value:,.0f}"
    except (TypeError, ValueError):
        return f"Rp {value}"


def _status_badge(status: str) -> str:
    status = (status or "unknown").lower()
    if status == "healthy":
        return f"<span class=\"status-badge healthy\">{status.upper()}</span>"
    if status in ("degraded", "warning"):
        return f"<span class=\"status-badge degraded\">{status.upper()}</span>"
    return f"<span class=\"status-badge unhealthy\">{status.upper()}</span>"


st.markdown("""
<style>
    .mission-header { font-size: 2.2rem; font-weight: 800; color: #1f1f1f; }
    .mission-sub { font-size: 1rem; color: #666; }
    .card { background: #ffffff; border-radius: 12px; padding: 1rem; border: 1px solid #e6e6e6; }
    .severity-critical { border-left: 5px solid #dc3545; }
    .severity-high { border-left: 5px solid #fd7e14; }
    .severity-warning { border-left: 5px solid #ffc107; }
    .severity-info { border-left: 5px solid #17a2b8; }
    .status-badge { font-size: 0.75rem; padding: 2px 8px; border-radius: 12px; font-weight: 600; }
    .healthy { background: #d4edda; color: #155724; }
    .degraded { background: #fff3cd; color: #856404; }
    .unhealthy { background: #f8d7da; color: #721c24; }
    .insight-card { padding: 0.75rem 1rem; border-radius: 8px; margin-bottom: 0.5rem; }
    .insight-critical { background: #f8d7da; color: #721c24; }
    .insight-high { background: #ffe5d9; color: #7a2e0b; }
    .insight-warning { background: #fff3cd; color: #856404; }
    .insight-info { background: #d1ecf1; color: #0c5460; }
    .section-title { font-size: 1.1rem; font-weight: 700; margin-top: 1rem; margin-bottom: 0.5rem; }
</style>
""", unsafe_allow_html=True)


# ---------------------------------------------------------------------------
# Sidebar navigation
# ---------------------------------------------------------------------------
st.sidebar.markdown("## 🎯 CommerceOS")
st.sidebar.page_link("pages/mission_control.py", label="Command Center", icon="🎯")
st.sidebar.page_link("pages/intelligence.py", label="Intelligence", icon="💡")
st.sidebar.page_link("pages/decisions.py", label="Decisions", icon="⚖️")
st.sidebar.page_link("pages/executions.py", label="Executions", icon="⚙️")
st.sidebar.page_link("pages/knowledge.py", label="Knowledge", icon="🧠")
st.sidebar.page_link("pages/sop_rules.py", label="SOP & Rules", icon="📜")
st.sidebar.page_link("pages/experiments.py", label="Experiments", icon="🧪")
st.sidebar.page_link("pages/operations.py", label="Operations", icon="🖥️")
st.sidebar.page_link("pages/analytics.py", label="Analytics", icon="📊")
st.sidebar.page_link("pages/timeline.py", label="Timeline", icon="📅")
st.sidebar.divider()

if st.sidebar.button("🔄 Refresh Data", width='stretch'):
    st.cache_resource.clear()
    st.rerun()

st.sidebar.caption(f"Store: `{STORE_ID}`")

# ---------------------------------------------------------------------------
# Load data
# ---------------------------------------------------------------------------
session = _get_session()
service = WebCOODashboardService(session, store_id=STORE_ID)
data = service.get_command_center()

# ---------------------------------------------------------------------------
# Header
# ---------------------------------------------------------------------------
col_header, col_status = st.columns([3, 1])
with col_header:
    st.markdown('<p class="mission-header">🎯 Command Center</p>', unsafe_allow_html=True)
    st.markdown('<p class="mission-sub">Everything that matters right now.</p>', unsafe_allow_html=True)

with col_status:
    st.markdown(_status_badge(data.overall_status), unsafe_allow_html=True)
    st.caption(f"Generated: {data.generated_at[:19]}")

st.divider()

# ---------------------------------------------------------------------------
# Business Today
# ---------------------------------------------------------------------------
st.markdown('<p class="section-title">📈 Business Today</p>', unsafe_allow_html=True)
bt = data.business_today
kpi_cols = st.columns(6)
with kpi_cols[0]:
    st.metric("Revenue", _currency(bt.get("revenue", 0)))
with kpi_cols[1]:
    st.metric("Gross Profit", _currency(bt.get("gross_profit", 0)))
with kpi_cols[2]:
    st.metric("Orders", bt.get("orders", 0))
with kpi_cols[3]:
    st.metric("Ad Spend", _currency(bt.get("ad_spend", 0)))
with kpi_cols[4]:
    st.metric("ROAS", f"{bt.get('roas', 0):.2f}x")
with kpi_cols[5]:
    st.metric("AOV", _currency(bt.get("aov", 0)))

if bt.get("temporary"):
    st.caption('⚠️ Some metrics are computed from canonical tables because materialized KPIs are missing.')

st.divider()

# ---------------------------------------------------------------------------
# Health
# ---------------------------------------------------------------------------
st.markdown('<p class="section-title">🩺 Health</p>', unsafe_allow_html=True)
health = data.health
hc = st.columns(5)
with hc[0]:
    st.metric("Overall Status", health.get("overall_status", "unknown").upper())
with hc[1]:
    st.metric("Open Alerts", health.get("open_alerts_count", 0))
with hc[2]:
    st.metric("Stale Entities", len(health.get("stale_entities", [])))
with hc[3]:
    st.metric("Failed Jobs (24h)", health.get("failed_jobs_count", 0))
with hc[4]:
    st.metric("Latest Sync", health.get("latest_sync", "—"))

if health.get("stale_entities"):
    stale = health["stale_entities"]
    st.warning(f"Stale data: {', '.join(stale)}")

st.divider()

# ---------------------------------------------------------------------------
# Attention Required
# ---------------------------------------------------------------------------
st.markdown('<p class="section-title">🚨 Attention Required</p>', unsafe_allow_html=True)
attention = data.attention

alerts = attention.get("critical_alerts", []) + attention.get("high_alerts", [])
if alerts:
    for alert in alerts[:5]:
        severity = alert.get("severity", "warning")
        card_class = f"severity-{severity}" if severity in ("critical", "high", "warning", "info") else "severity-warning"
        with st.container():
            st.markdown(f'<div class="card {card_class}">', unsafe_allow_html=True)
            st.markdown(f"**[{severity.upper()}] {alert.get('title', 'Alert')}**")
            st.caption(alert.get("description", "—"))
            st.markdown("</div>", unsafe_allow_html=True)
else:
    st.success("No critical or high alerts right now.")

priority_decisions = attention.get("priority_decisions", [])
if priority_decisions:
    st.markdown("**Priority Decisions**")
    for decision in priority_decisions[:3]:
        severity = decision.get("severity", "info")
        card_class = f"severity-{severity}" if severity in ("critical", "high", "warning", "info") else "severity-info"
        with st.container():
            st.markdown(f'<div class="card {card_class}">', unsafe_allow_html=True)
            cols = st.columns([3, 2])
            with cols[0]:
                st.markdown(f"**{decision.get('title', 'Decision')}**")
                st.caption(decision.get("description", "—")[:200])
            with cols[1]:
                st.markdown(f"**Action:** {decision.get('recommended_action', '—')}")
                st.markdown(f"**Impact:** {decision.get('expected_impact', '—')}")
            st.markdown("</div>", unsafe_allow_html=True)
else:
    st.info("No priority decisions pending.")

low_stock = attention.get("low_stock_skus", [])
if low_stock:
    st.markdown("**Low Stock Risk**")
    df = pd.DataFrame(low_stock)
    st.dataframe(df, width='stretch', hide_index=True)
else:
    st.success("No low-stock SKUs within the lookahead window.")

failed_jobs = attention.get("failed_jobs", [])
if failed_jobs:
    st.markdown("**Failed Jobs (24h)**")
    st.dataframe(pd.DataFrame(failed_jobs), width='stretch', hide_index=True)

st.divider()

# ---------------------------------------------------------------------------
# COO Brief
# ---------------------------------------------------------------------------
st.markdown('<p class="section-title">🎙️ COO Brief</p>', unsafe_allow_html=True)
coo = data.coo_brief
st.markdown(coo.get("answer", "—"))
if coo.get("warnings"):
    for warning in coo["warnings"]:
        st.caption(f"⚠️ {warning}")
if coo.get("suggested_actions"):
    st.markdown("**Suggested actions:**")
    for action in coo["suggested_actions"]:
        st.markdown(f"- {action}")

if data.errors:
    with st.expander("Subsystem warnings"):
        for error in data.errors:
            st.caption(f"⚠️ {error}")

st.divider()
st.caption("CommerceOS Web COO Dashboard | Command Center")
