"""Monitoring bounded context: health checks, alerts, snapshots.

This module defines the database models used by the Monitoring Layer. They are
intended to be storage-agnostic SQLAlchemy models; PostgreSQL-specific features
are avoided so tests can run against SQLite.
"""
from commerceos.shared.value_objects.primitives import utc_now

from datetime import datetime, timezone
from typing import Optional, List

from sqlalchemy import String, Text, Integer, DateTime, JSON, Index, Numeric
from sqlalchemy.orm import Mapped, mapped_column

from commerceos.platform.database.models import Base, TimestampMixin, new_uuid


class HealthCheck(Base, TimestampMixin):
    """One point-in-time health check result for a component instance."""

    __tablename__ = "health_checks"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_uuid)
    component: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    component_instance: Mapped[Optional[str]] = mapped_column(String(255), nullable=True, index=True)
    check_type: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    status: Mapped[str] = mapped_column(String(20), nullable=False, index=True)
    severity: Mapped[str] = mapped_column(String(20), nullable=False, default="info")
    message: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    metadata_: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)
    checked_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=lambda: utc_now()
    )

    __table_args__ = (
        Index("ix_health_checks_component_checked_at", "component", "checked_at"),
    )


class Alert(Base, TimestampMixin):
    """Operational alert that is deduplicated by category+component+instance."""

    __tablename__ = "alerts"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_uuid)
    category: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    component: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    component_instance: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    severity: Mapped[str] = mapped_column(String(20), nullable=False, index=True)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="open", index=True)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    metadata_: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)
    first_seen: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=lambda: utc_now()
    )
    last_seen: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=lambda: utc_now(), onupdate=lambda: utc_now()
    )
    resolved_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)

    __table_args__ = (
        Index("ix_alerts_open", "status", "severity", "last_seen"),
    )


class HealthSnapshot(Base, TimestampMixin):
    """Aggregated system health snapshot generated by the monitoring service."""

    __tablename__ = "health_snapshots"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_uuid)
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=lambda: utc_now()
    )
    overall_status: Mapped[str] = mapped_column(String(20), nullable=False, default="unknown")
    data_quality_score: Mapped[Optional[float]] = mapped_column(Numeric(5, 4), nullable=True)
    freshness_score: Mapped[Optional[float]] = mapped_column(Numeric(5, 4), nullable=True)
    availability_score: Mapped[Optional[float]] = mapped_column(Numeric(5, 4), nullable=True)
    summary: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)


class JobExecution(Base, TimestampMixin):
    """Log of scheduled/operational job executions for scheduler health checks."""

    __tablename__ = "job_executions"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_uuid)
    job_name: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    job_group: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="completed")
    started_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    finished_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    duration_seconds: Mapped[Optional[float]] = mapped_column(Numeric(10, 3), nullable=True)
    metadata_: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)

    __table_args__ = (
        Index("ix_job_executions_name_finished", "job_name", "finished_at"),
    )
